[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"  # Ubah ke versi yang tersedia di sistem Anda
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
lisk_sepolia = "${LISK_SEPOLIA_RPC_URL}"

[etherscan]
lisk_sepolia = { key = "${ETHERSCAN_API_KEY}" }

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]